version: "3.9"
services:
  github-runner-exporter:
    container_name: github-runner-exporter
    build: .
    image: "github-runner-exporter:latest"
    ports:
      - "8000:8000"
    environment:
      OWNER: ${OWNER}
      LOGLEVEL: "${LOGLEVEL:-DEBUG}"
      PRIVATE_GITHUB_TOKEN: "${PRIVATE_GITHUB_TOKEN}"